version: '3'

services:
  db:
    container_name: nest-example-db
    hostname: nest-example-db
    image: mysql:5.7
    volumes:
      - nest_example_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest_example
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
  api:
    container_name: nest-example-api
    hostname: nest-example-api
    build: 
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./src:/var/www/nest-example/src
    ports:
      - "3000:3000"
    env_file: "./docker/environments"
    depends_on:
      - db

volumes:
  nest_example_data:
