FROM node:9

RUN npm i -g typescript ts-node nodemon

WORKDIR /var/www/nest-example
ADD package.json /var/www/nest-example
ADD yarn.lock /var/www/nest-example
RUN yarn install

ADD . /var/www/nest-example

EXPOSE 3000

CMD ["docker/start.sh"]

