version: '2.1'

services:
  db:
    container_name: recicle-chain-db
    hostname: recicle-chain-db
    image: mysql:5.7
    volumes:
      - recicle_db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: recicle_chain
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
  api:
    container_name: recicle-chain-api
    hostname: recicle-chain-api
    build: ./
    volumes:
      - ./src:/var/www/recicle-chain-api/src
      - ./docker:/var/www/recicle-chain-api/docker
    ports:
      - "3000:3000"
    env_file: "./docker/environments"
    depends_on:
      - db

volumes:
  recicle_db_data:
