version: '2.1'

services:
  sponsors:
    container_name: sponsors
    hostname: sponsors
    environment:
      DB_ENV: develop
    build: 
      context: .
      dockerfile: ./Dockerfile
    depends_on: 
      - db
    ports:
      - "8080:8080"
  
  api:
    container_name: sponsors_api
    hostname: sponsors_api
    environment:
      DB_ENV: develop
    build: 
      context: .
      dockerfile: ./Dockerfile.api
    depends_on: 
      - db
    ports:
      - "8080:8080"

  db:
      container_name: sponsors_db
      hostname: sponsors_db
      image: mysql:5.7
      volumes:
        - sponsors_db_data:/var/lib/mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: sponsors
        MYSQL_USER: root
        MYSQL_PASSWORD: root
      ports:
        - "3306:3306"

volumes:
  sponsors_db_data:
