version: '3'

services:
  api:
    container_name: tron_api
    hostname: tron_api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/tron/src
    ports:
      - "3000:3000"
    env_file: "./docker/environments"
  web:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
