version: '2.1'

services:
  koa-db:
    container_name: example-db
    hostname: example-db
    image: mysql:5.7
    volumes:
      - koa_db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
  api:
    container_name: koa2-example-api
    hostname: koa2-example-api
    build: 
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - ./src:/var/www/koa2-example/src
    ports:
      - "8000:8000"
    env_file: "./docker/environments"
    depends_on:
      - koa-db
volumes:
  koa_db_data:
