export const FETCH_TASKS_REQUEST = '@@CAPTIFY/HOME/FETCH_TASKS_REQUEST';
export const FETCH_TASKS_SUCCESS = '@@CAPTIFY/HOME/FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_FAIL = '@@CAPTIFY/HOME/FETCH_TASKS_FAIL';

export const CREATE_TASKS_REQUEST = '@@CAPTIFY/HOME/CREATE_TASKS_REQUEST';
export const CREATE_TASKS_SUCCESS = '@@CAPTIFY/HOME/CREATE_TASKS_SUCCESS';
export const CREATE_TASKS_FAIL = '@@CAPTIFY/HOME/CREATE_TASKS_FAIL';

export const DELETE_TASKS_REQUEST = '@@CAPTIFY/HOME/DELETE_TASKS_REQUEST';
export const DELETE_TASKS_SUCCESS = '@@CAPTIFY/HOME/DELETE_TASKS_SUCCESS';
export const DELETE_TASKS_FAIL = '@@CAPTIFY/HOME/DELETE_TASKS_FAIL';

